// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DialogUserIDListGetOperation  OperationName = "DialogUserIDListGet"
	DialogUserIDSendPostOperation OperationName = "DialogUserIDSendPost"
)
