// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DialogUserIDListGet implements GET /dialog/{user_id}/list operation.
//
// GET /dialog/{user_id}/list
func (UnimplementedHandler) DialogUserIDListGet(ctx context.Context, params DialogUserIDListGetParams) (r DialogUserIDListGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DialogUserIDSendPost implements POST /dialog/{user_id}/send operation.
//
// POST /dialog/{user_id}/send
func (UnimplementedHandler) DialogUserIDSendPost(ctx context.Context, req OptDialogUserIDSendPostReq, params DialogUserIDSendPostParams) (r DialogUserIDSendPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
