linters:
  disable:
    - godox
    - funlen
    - exhaustive
  enable:
    - forbidigo
    - gosec
    - wrapcheck
  presets:
    - bugs
    - error
    - complexity
    - performance
    - unused
    - comment
    - sql

linters-settings:
  wrapcheck:
    ignoreSigRegexps:
      - \.Wrap.*Error\(
      - \.*errors.NewWithValue\(
      - \.*errors.New\(
  cyclop:
    max-complexity: 15
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
  forbidigo:
    forbid:
      - p: ^fmt\.Print.*$
        msg: Do not commit print statements.

issues:
  exclude-dirs:
    - docker
    - docs
    - migrations
    - vendor
    # дериктории которые надо добавить.
    - internal/mocks
    - tests # интеграционные тесты.

run:
  tests: false
