linters:
  disable:
    - makezero
    - contextcheck
    - godox # для dev не нужен, а вот для прода лучше включить.
    - funlen
    - exhaustive
    - perfsprint
  # enable:
  #   - gosec
  #   - wrapcheck
  presets:
    - bugs
    - error
    - complexity
    - performance
    - unused
    - comment
    - sql

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - apierrors.New(
      - apierrors.NewWithValue(
      - httperrors.New(
    ignoreSigRegexps:
      - \.Wrap.*Error\(
    ignorePackageGlobs:
      - internal/pkg/httperrors
      - internal/pkg/apierrors

  cyclop:
    max-complexity: 15

  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write

  exhaustive:
    default-signifies-exhaustive: true

run:
  tests: false

issues:
  exclude-dirs:
    # пакет исключен до рефакторинга
    - internal/pkg/lock
    # пакеты исключены из проверки, т.к. в настройках линтеров нет возможности настроить исключения.
    # - internal/pkg/httperrors
    # - internal/pkg/apierrors
    # - internal/pkg/tx
    # моки
    - internal/mocks
    # дериктории...
    - ci
    - docker
    - docs
    - fixtures
    - migrations
    - tmp
