app:
  name: otus-highload
  shutdown_timeout: 5
  web:
    port: 8080
    read_timeout: 5
    write_timeout: 5
  token:
    secret: secret
    expire: 43200

log:
  level: info
  format: console

db:
  host: localhost
  port: 5432
  database: main
  user: root
  password: root

otlp:
  metrics_port: 4318
  traces_url: http://localhost:4317
  service_name: social-network
  traces_enabled: false

redis:
  host: localhost
  port: 6379
