app:
  name: social-network
  shutdown_timeout_sec: 5
  web:
    port: 8000
    read_timeout_sec: 15
    write_timeout_sec: 15
    retry_after_sec: 5
  token:
    secret: secret
    expire_sec: 43200

log:
  level: debug
  format: console

db:
  host: localhost
  port: 5432
  database: main
  user: root
  password: root
  exec_mode: SIMPLE_PROTOCOL

otlp:
  metrics_port: 4318
  traces_url: http://localhost:4317
  traces_enabled: false

redis:
  host: localhost
  port: 6379
