server {
    listen 8100;

    root /usr/share/nginx/html;
    index feed.html;

    # Static files
    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy API to socialnetwork
    location ~* ^/(login|user|friend|post|dialog) {
        proxy_pass         http://app:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
