version: "3.6"

services:
  app:
    build: 
      context: ./dev
    ports:
      - 8000:8000
      - 4318:4318
      - 2345:2345
    volumes:
      - ./..:/app
    environment:
      ENVIRONMENT: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: main
      DB_USER: root
      DB_PASSWORD: root
      TZ: Europe/Moscow
    depends_on:
      - postgres          

  postgres:
    image: postgres:14-bullseye
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      TZ: Europe/Moscow

  redis:
    image: redis:5.0.7

  adminer:
    image: adminer:latest
    ports:
      - 8003:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8002:80
    logging:
      driver: none      
    depends_on:
      - postgres      