version: "3.6"

services:
  app:
    build:
      context: ./socialnetwork
    ports:
      - 8000:8000
      - 4318:4318
      - 2345:2345
    volumes:
      - ./..:/app
    environment:
      ENVIRONMENT: dev
      CONFIG_PATH: /app/cmd/socialnetwork
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: main
      DB_USER: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      NATS_HOST: nats
      NATS_PORT: 4222
      TZ: Europe/Moscow
    depends_on:
      - postgres
      - redis
      - nats

  postgres:
    image: postgres:14-bullseye
    command: -c 'max_connections=200'
    ports:
      - 5432:5432    
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      TZ: Europe/Moscow

  example:
    image: nginx:1.27-alpine
    ports:
      - "8100:8100"
    volumes:
      - ./../example:/usr/share/nginx/html:ro
      - ./example/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  nats:
    image: nats:2.10-alpine
    command: "-js -m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"

  wsnotifier:
    build:
      context: ./wsnotifier
    ports:
      - "8002:8002"
    volumes:
      - ./..:/app
    environment:
      ENVIRONMENT: dev
      CONFIG_PATH: /app/cmd/wsnotifier
      NATS_HOST: nats
      NATS_PORT: 4222
      APP_TOKEN_SECRET: secret
      TZ: Europe/Moscow
    depends_on:
      - nats

  redis:
    image: redis:5.0.7

  adminer:
    image: adminer:latest
    ports:
      - 8003:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  tarantool:
    image: tarantool/tarantool:2.11
    command: tarantool /opt/tarantool/app.lua
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/app.lua

  chat:
    build:
      context: ./chat
    ports:
      - 8001:8001
      - 2346:2345
    volumes:
      - ./..:/app
    environment:
      ENVIRONMENT: dev
      CONFIG_PATH: /app/cmd/chat
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3301
      TZ: Europe/Moscow
    depends_on:
      - tarantool


  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=root@mail.ru
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 8002:80
  #   logging:
  #     driver: none      
  #   depends_on:
  #     - postgres      