version: "3.6"

services:
  app:
    build:
      context: ./socialnetwork
    ports:
      - 8000:8000
      - 4318:4318
      - 2345:2345
    volumes:
      - ./..:/app
    environment:
      ENVIRONMENT: dev
      CONFIG_PATH: /app/cmd/socialnetwork
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: main
      DB_USER: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      TZ: Europe/Moscow
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-bullseye
    command: -c 'max_connections=200'
    ports:
      - 5432:5432    
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      TZ: Europe/Moscow

  redis:
    image: redis:5.0.7

  adminer:
    image: adminer:latest
    ports:
      - 8003:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  citus-worker1:
    image: citusdata/citus:13.0
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dialogs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dialogs"]
      interval: 5s
      timeout: 5s
      retries: 10

  citus-worker2:
    image: citusdata/citus:13.0
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dialogs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dialogs"]
      interval: 5s
      timeout: 5s
      retries: 10

  chat:
    build:
      context: ./chat
    ports:
      - 8001:8001
      - 2346:2345
    volumes:
      - ./..:/app
    environment:
      ENVIRONMENT: dev
      CONFIG_PATH: /app/cmd/chat
      DIALOG_DB_HOST: citus-coordinator
      DIALOG_DB_PORT: 5432
      DIALOG_DB_NAME: dialogs
      DIALOG_DB_USER: root
      DIALOG_DB_PASSWORD: root
      TZ: Europe/Moscow
    depends_on:
      citus-coordinator:
        condition: service_started

  citus-coordinator:
    image: citusdata/citus:13.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dialogs
    volumes:
      - ./citus/init.sql:/docker-entrypoint-initdb.d/10_init.sql
    depends_on:
      citus-worker1:
        condition: service_healthy
      citus-worker2:
        condition: service_healthy

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=root@mail.ru
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 8002:80
  #   logging:
  #     driver: none      
  #   depends_on:
  #     - postgres      