app:
  name: chat
  shutdown_timeout_sec: 5
  web:
    port: 8001
    read_timeout_sec: 600
    write_timeout_sec: 600
    retry_after_sec: 5
  token:
    secret: secret
    expire_sec: 43200

log:
  level: info
  format: json

db:
  host: citus-coordinator
  port: 5432
  database: dialogs
  user: root
  password: root
  max_conns: 50
  min_conns: 5
  exec_mode: MODE_SIMPLE

otlp:
  metrics_port: 4319
  traces_url: http://localhost:4317
  traces_enabled: false
