app:
  name: chat
  shutdown_timeout_sec: 5
  web:
    port: 8001
    read_timeout_sec: 600
    write_timeout_sec: 600
    retry_after_sec: 5
  token:
    secret: secret
    expire_sec: 43200

log:
  level: info
  format: json

otlp:
  metrics_port: 4319
  traces_url: http://localhost:4317
  traces_enabled: false

tarantool:
  host: tarantool
  port: 3301