// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DialogUserIDListGetOperation   OperationName = "DialogUserIDListGet"
	DialogUserIDSendPostOperation  OperationName = "DialogUserIDSendPost"
	FriendDeleteUserIDPutOperation OperationName = "FriendDeleteUserIDPut"
	FriendSetUserIDPutOperation    OperationName = "FriendSetUserIDPut"
	LoginPostOperation             OperationName = "LoginPost"
	PostCreatePostOperation        OperationName = "PostCreatePost"
	PostDeleteIDPutOperation       OperationName = "PostDeleteIDPut"
	PostFeedGetOperation           OperationName = "PostFeedGet"
	PostGetIDGetOperation          OperationName = "PostGetIDGet"
	PostUpdatePutOperation         OperationName = "PostUpdatePut"
	UserGetIDGetOperation          OperationName = "UserGetIDGet"
	UserRegisterPostOperation      OperationName = "UserRegisterPost"
	UserSearchGetOperation         OperationName = "UserSearchGet"
)
